### ISSUE TITLE
Bug in upload of RNA cases to Scout

### ISSUE THREAD

**Issue by SofiaOtero** [Clinical-Genomics/cg#1870]
## Description

When uploading a RNA case to Scout the cg upload -f command ran without any issues even though the connected DNA case was not sequenced yet, hence not available on Scout yet.  

This is the output I got:
````
----------------- UPLOAD RNA TO SCOUT -----------------------
----------------- UPLOAD RNA FUSION REPORT TO SCOUT -----------------------
Fetch latest version from bundle immunecrow
Fetching files with tags in [fusion,clinical]
Fetching files from version 136265
Clinical fusion report immunecrow/2023-03-25/immunecrow_report.selected.pdf found
Upload Clinical fusion report finished!
----------------- UPLOAD RNA JUNCTIONS TO SCOUT -----------------------
Fetch latest version from bundle immunecrow
Fetching files with tags in [junction,bed,ACC11597A4]
Fetching files from version 136265
Splice junctions bed file immunecrow/2023-03-25/ACC11597A4_lanes_1234_star_sorted_sj.bed.gz found
Upload splice junctions bed file finished!
Fetch latest version from bundle immunecrow
Fetching files with tags in [coverage,bigwig,ACC11597A4]
Fetching files from version 136265
RNA coverage bigwig file immunecrow/2023-03-25/ACC11597A4_lanes_1234_star_sorted_sj.bigWig found
Upload RNA coverage bigwig file finished!
Upload of case immunecrow was successful. Setting uploaded at to 2023-03-29 13:38:02.300714
immunecrow - uploaded at set to 2023-03-29 13:38:02
immunecrow analysis has been successfully uploaded
````
So it looks like the RNA analysis was uploaded to Scout though it wasn't.

## This can be closed when

The command writes an error about the DNA case not being uploaded to Scout yet, similar to the error we get when there is no DNA case connected to the RNA case.

**Comment by SofiaOtero** [comment]
@peterpru @seallard could this be connected to your recent merge?

**Comment by peterpru** [comment]
It should spit out an error, saying something like scout report not found for the DNA case, which it has been doing previously. If you refer to this, https://github.com/Clinical-Genomics/cg/pull/1852, the function I made there has not been put into use yet.

**Comment by seallard** [comment]
It might be, I will take a look when I'm back next week!

**Comment by seallard** [comment]
It seems like the issue has been resolved since then. @SofiaOtero noticed the following output when the DNA case has not sequences yet:

```
----------------- UPLOAD RNA TO SCOUT -----------------------
----------------- UPLOAD RNA FUSION REPORT TO SCOUT -----------------------
Failed to upload files for RNA case: unexpected number of DNA sample matches for subject_id: G000386542. Number of matches: 0
```

We still want to implement a test that verifies that the expected error is raised.

**Comment by peterpru** [comment]
Hi, this issue is not resolved, see image below. I think happens when there is a connected DNA sample, but no connected DNA scout case or DNA analysis. Once the DNA case progresses, it will look as expected in the second post from Sofia.

<img width="935" alt="image" src="https://github.com/Clinical-Genomics/cg/assets/57712924/9d7c1088-277d-444a-a715-66ab72cb1367">

**Comment by Vince-janv** [comment]
Closing due to inactivity. Reopen and answer the question below if you want this prioritised.

Concerning the reported bug:
- How often does the bug occur?
- Who does it affect?
- If there is a workaround:
    - What is it?
    - How long does it take?
